import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { PassThrough } from "stream";
import path from "path";
import { validateApiToken } from "@/lib/apiAuth";

interface CarData {
  id?: string;
  vin: string;
  brand: string;
  model: string;
  year: string;
  mileage: string;
  price: string;
  currency: string;
  registrationCountry: string;
  fuelType: string;
  color: string;
  bodyType: string;
  version: string;
  vehicleHistory: string;
  stolenCheck: string;
  vinDecoder: string;
}

export async function POST(req: NextRequest) {
  const authError = validateApiToken(req)
  if (authError) return authError

  const data: CarData = await req.json();

  const stream = new PassThrough();

  // fonts
  const fontRegular = path.join(process.cwd(), "public/fonts/Roboto-Regular.ttf");
  const fontBold = path.join(process.cwd(), "public/fonts/Roboto-Bold.ttf");

  // init
  const doc = new PDFDocument({
    margin: 40,
    font: path.join(process.cwd(), "public/fonts/Roboto-Regular.ttf"),
  });

  doc.pipe(stream);

  // load fonts
  doc.registerFont("Regular", fontRegular);
  doc.registerFont("Bold", fontBold);

  // header
  doc.font("Bold").fontSize(20).text("Car Report", { align: "center" });
  doc.moveDown(1.5);

  // helper
  const addLine = (label: string, value: any) => {
    doc
      .font("Bold")
      .fontSize(12)
      .text(label + ": ", { continued: true })
      .font("Regular")
      .text(value || "N/A");
    doc.moveDown(0.5);
  };

  // info
  addLine("VIN", data.vin);
  addLine("Brand", data.brand);
  addLine("Model", data.model);
  addLine("Year", data.year);
  addLine("Mileage", data.mileage);
  addLine(
    "Price",
    data.price ? `${data.price} ${data.currency}` : "N/A"
  );
  addLine("Registration Country", data.registrationCountry);
  addLine("Fuel Type", data.fuelType);
  addLine("Color", data.color);
  addLine("Body Type", data.bodyType);
  addLine("Version", data.version);

  doc.moveDown();

  // links
  addLine("Vehicle History", data.vehicleHistory);
  addLine("Stolen Check", data.stolenCheck);
  addLine("VIN Decoder", data.vinDecoder);

  doc.save()

  // branding
  doc.font("Bold")
    .fontSize(10)
    .text("Generated by VinPro", 0, doc.page.height - 60, {
      align: "center",
    })

  doc.restore()

  doc.end();

  return new Response(stream as any, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename=car-${data.vin}.pdf`,
    },
  });
}